### ISSUE TITLE
HTML Page Styling CSS

### ISSUE THREAD

**Issue by Loosekonnection** [Loosekonnection/believe#3]
Create styling for the HTML template that will be consistent across the site

Suggestion (Font - Bradley Hand ITC)

Dave - Added a colour to the NAV and Footer.
Dave - Added a font named Bradley Hand ITC.

**Comment by sallyxp** [comment]
Although Maryum has been responsible for this file creation, all team members have amended/added different style attributes to various elements as part of their development work.
