### ISSUE TITLE
Write "add" functionality to page

### ISSUE THREAD

**Issue by Robbie-Bridgwater** [Loosekonnection/believe#30]
- Write code that will allow you to add what you have searched for into the meal div
- Then code which allows you to add the entire content of meal div to day div
- Then code which allows you to add the entire content of day div to week div

**Comment by sallyxp** [comment]
This issue has been resolved successfully, code has been created which allows the successful search and addition of food items,  The cards selected can then be used to produce total information of  Calories, Protein, Fat & Carbohydrates.
