### ISSUE TITLE
Site Banner/Hero Image

### ISSUE THREAD

**Issue by Loosekonnection** [Loosekonnection/believe#4]
research a suitable royalty free wellbeing logo.

**Comment by sallyxp** [comment]
![hero](https://user-images.githubusercontent.com/74880431/107033154-ca3d8f80-67ac-11eb-80d2-4703b11af0bb.png)

Believe Logo

**Comment by sallyxp** [comment]
'Believe.'  logo for Believe Wellbeing project.
