### ISSUE TITLE
Inspirational Modal

### ISSUE THREAD

**Issue by Loosekonnection** [Loosekonnection/believe#6]
Research where this sits within the code.
AJAX setup for API call for quotes.

Have created a Modal in the index.html file, then added CSS for the styling, and an event listener for the closure of the modal. 

Added a mouse over effect to the continue button. and Materialise font-flow class.

**Comment by sallyxp** [comment]
Sally created a Modal box using Materialize.  Clicking is optional, it has the text 'Just starting? Click Here ...' and appears at the top of the opening page.
